FROM informatievlaanderen/standaardenregister-base:1.1.7 as BUILD

WORKDIR /app

ADD . /app

RUN npm run build

FROM node:18-alpine 
WORKDIR /app
EXPOSE 3000
COPY --from=BUILD /app/.output /app
CMD ["node", "./server/index.mjs"]