FROM node:18-alpine 

ADD . /app
WORKDIR /app

ARG NPM_AUTH_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > /app/.npmrc 

RUN apk update 
RUN apk add python3 vim make gcc g++ curl

RUN yarn install

RUN yarn add @govflanders/vl-ui-design-system-vue3
RUN yarn add @govflanders/vl-ui-design-system-style

# force a build
RUN yarn install --force 