FROM node:20-alpine

ADD . /app
WORKDIR /app

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /app/.npmrc

RUN apk update
RUN apk add python3 vim make gcc g++ curl

RUN yarn install

# force a build
RUN yarn install --force
