FROM node:22-slim

ADD . /app
WORKDIR /app

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /app/.npmrc

RUN apt-get update && apt-get install -y \
    python3 \
    vim \
    make \
    gcc \
    g++ \
    curl \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN yarn install
