ARG VERSION
FROM informatievlaanderen/standaardenregister-base:${VERSION} as BUILD

WORKDIR /app

ADD . /app

RUN npm run build

FROM node:22-slim
WORKDIR /app
EXPOSE 3000
COPY --from=BUILD /app/.output /app
CMD ["node", "./server/index.mjs"]
