version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:20.11' # Use the CircleCI Node.js image
    steps:
      - checkout # Check out the code in the project directory
      - add_ssh_keys:
          fingerprints:
            - '84:ef:18:e6:4c:b3:fa:38:4e:d2:47:09:e9:be:0f:e6'
      - restore_cache: # Restore saved dependency cache if it exists
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache: # Save dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - setup_remote_docker
      - run:
          name: Build standaardenregister Base Image
          command: make build-base
      - run:
          name: Build standaardenregister Image
          command: make build
workflows:
  version: 2
  build:
    jobs:
      - build
